name: Suibhne
options:
  bundleIdPrefix: app.suibhne
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"

targets:
  Suibhne:
    type: application
    platform: macOS
    sources:
      - path: Suibhne
        excludes:
          - "**/.DS_Store"
      - path: Shared
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.suibhne.app
        PRODUCT_NAME: Suibhne
        INFOPLIST_FILE: Suibhne/Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: Suibhne/Resources/Suibhne.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        COMBINE_HIDPI_IMAGES: YES
        LD_RUNPATH_SEARCH_PATHS: 
          - "$(inherited)"
          - "@executable_path/../Frameworks"
        ENABLE_HARDENED_RUNTIME: YES
        LSUIElement: YES
